<?php
/**
 * Backup & Restore — CSRF Regression + Functional Invariants
 *
 * Locks in the Option-A fix for the "Invalid or expired request. Refresh the
 * page and try again." failure on every action of the Backup & Restore page
 * (Generate Backup, Restore from File, Upload & Restore, Delete).
 *
 * Root cause that this suite guards against:
 *   - The page used a custom $_SESSION['backup_csrf_token'] (generated by a
 *     local generateCsrfToken() helper) that was created server-side but
 *     NEVER echoed into the JS. The JS sent the global CSRF_TOKEN instead,
 *     and the API checked the custom token, so hash_equals() always failed.
 *
 * Fix that this suite enforces:
 *   - api/backup_actions.php uses the canonical csrf_check() helper from
 *     helpers.php (§21 of .claude/security.md). No custom token logic.
 *   - app/constant/settings/backup_restore.php no longer defines a custom
 *     token; its JS sends the global CSRF_TOKEN via the X-CSRF-Token header,
 *     which is exactly what csrf_check() reads.
 *
 * The suite also pins functional invariants (php -l, required actions,
 * required JS handlers, permission gates) so future edits don't silently
 * break the page in a different way.
 *
 * Run:  php tests/test_backup_restore_csrf_cli.php
 *   Exit 0 = all pass (safe to commit / push)
 *   Exit 1 = failures  (push blocked — fix before pushing)
 */

error_reporting(E_ALL & ~E_DEPRECATED);

$root     = dirname(__DIR__);
$failures = 0;
$passes   = 0;

function pass(string $m): void    { global $passes;   $passes++;   echo "  \033[32m✅\033[0m $m\n"; }
function fail(string $m): void    { global $failures; $failures++; echo "  \033[31m❌ $m\033[0m\n"; }
function section(string $t): void { echo "\n\033[1m── $t ──\033[0m\n"; }
function check(bool $cond, string $ok, string $ko): void { $cond ? pass($ok) : fail($ko); }

echo "\n\033[1m═══ Backup & Restore — CSRF Regression Guard ═══\033[0m\n";

$apiFile  = $root . '/api/backup_actions.php';
$uiFile   = $root . '/app/constant/settings/backup_restore.php';
$helpers  = $root . '/helpers.php';
$header   = $root . '/header.php';

// ─────────────────────────────────────────────────────────────────────────────
section('1. Both files exist and are syntactically valid PHP');
// ─────────────────────────────────────────────────────────────────────────────

foreach ([$apiFile, $uiFile, $helpers, $header] as $f) {
    $rel = str_replace($root . DIRECTORY_SEPARATOR, '', $f);
    check(is_file($f), "$rel exists", "$rel is missing");
}

foreach ([$apiFile, $uiFile] as $f) {
    $rel = str_replace($root . DIRECTORY_SEPARATOR, '', $f);
    $out = [];
    $code = 0;
    exec('php -l ' . escapeshellarg($f) . ' 2>&1', $out, $code);
    check($code === 0, "$rel passes php -l", "$rel has PHP syntax errors: " . implode(' | ', $out));
}

$api = is_file($apiFile) ? file_get_contents($apiFile) : '';
$ui  = is_file($uiFile)  ? file_get_contents($uiFile)  : '';
$hlp = is_file($helpers) ? file_get_contents($helpers) : '';
$hdr = is_file($header)  ? file_get_contents($header)  : '';

// ─────────────────────────────────────────────────────────────────────────────
section('2. Canonical csrf_check() helper is still in place');
// ─────────────────────────────────────────────────────────────────────────────

check(
    (bool) preg_match('/function\s+csrf_check\s*\(/', $hlp),
    'helpers.php declares csrf_check()',
    'helpers.php no longer declares csrf_check() — Option-A fix relies on it'
);

check(
    (bool) preg_match('/function\s+csrf_token\s*\(/', $hlp),
    'helpers.php declares csrf_token()',
    'helpers.php no longer declares csrf_token() — header.php depends on it'
);

check(
    str_contains($hlp, "\$_POST['_csrf']") && str_contains($hlp, "HTTP_X_CSRF_TOKEN"),
    'csrf_check() accepts both _csrf POST field and X-CSRF-Token header',
    'csrf_check() transport contract changed — backup page sends X-CSRF-Token; update accordingly'
);

check(
    str_contains($hdr, 'CSRF_TOKEN') && str_contains($hdr, 'csrf_token()'),
    'header.php exposes the global CSRF_TOKEN JS constant from csrf_token()',
    'header.php no longer exposes CSRF_TOKEN — backup page JS depends on it'
);

// ─────────────────────────────────────────────────────────────────────────────
section('3. api/backup_actions.php — Option-A fix invariants');
// ─────────────────────────────────────────────────────────────────────────────

check(
    !str_contains($api, 'backup_csrf_token'),
    'API no longer references the legacy $_SESSION[\'backup_csrf_token\']',
    'API still references backup_csrf_token — legacy CSRF leak NOT removed'
);

check(
    (bool) preg_match('/\bcsrf_check\s*\(\s*\)\s*;/', $api),
    'API invokes csrf_check();',
    'API does not call csrf_check() — CSRF protection is OFF or non-canonical'
);

check(
    !preg_match('/hash_equals\s*\(\s*\$_SESSION\[[\'"]backup_csrf_token/', $api),
    'API does not hand-roll hash_equals() against backup_csrf_token',
    'API still hand-rolls the broken CSRF comparison — Option-A not applied'
);

check(
    !str_contains($api, "Invalid or expired request"),
    'API no longer carries the hard-coded "Invalid or expired request" string',
    'API still ships the old CSRF rejection message — fix is incomplete'
);

check(
    str_contains($api, "require_once __DIR__ . '/../roots.php'"),
    'API still requires roots.php (which loads helpers.php → csrf_check)',
    'API no longer requires roots.php — csrf_check() will be undefined'
);

// ─────────────────────────────────────────────────────────────────────────────
section('4. api/backup_actions.php — all 4 actions still wired');
// ─────────────────────────────────────────────────────────────────────────────

foreach (['create_backup', 'restore_backup', 'delete_backup', 'upload_restore'] as $act) {
    check(
        (bool) preg_match('/case\s+[\'"]' . $act . '[\'"]\s*:/', $api),
        "API handles action: $act",
        "API no longer handles action: $act — backup page would break"
    );
}

check(
    (bool) preg_match("/canDelete\\s*\\(\\s*['\"]backup_restore['\"]\\s*\\)/", $api),
    'API enforces canDelete(\'backup_restore\') permission gate',
    'API has lost the backup_restore permission gate — anyone could create/restore'
);

// ─────────────────────────────────────────────────────────────────────────────
section('5. app/constant/settings/backup_restore.php — page invariants');
// ─────────────────────────────────────────────────────────────────────────────

check(
    !preg_match('/function\s+generateCsrfToken\s*\(/', $ui),
    'Page no longer defines local generateCsrfToken()',
    'Page still defines generateCsrfToken() — legacy duplicate CSRF system'
);

check(
    !str_contains($ui, "\$_SESSION['backup_csrf_token']")
 && !str_contains($ui, '$_SESSION["backup_csrf_token"]'),
    'Page no longer reads or writes $_SESSION[\'backup_csrf_token\']',
    'Page still touches $_SESSION[\'backup_csrf_token\'] — Option-A incomplete'
);

check(
    !preg_match('/\$csrfToken\s*=\s*generateCsrfToken\s*\(/', $ui),
    'Page no longer calls generateCsrfToken()',
    'Page still calls the removed generateCsrfToken() — fatal error at runtime'
);

check(
    (bool) preg_match("/autoEnforcePermission\\s*\\(\\s*['\"]backup_restore['\"]\\s*\\)/", $ui),
    'Page still enforces backup_restore permission via autoEnforcePermission',
    'Page no longer enforces backup_restore permission — non-admins could load it'
);

check(
    str_contains($ui, 'if (!isAdmin())'),
    'Page still has the isAdmin() second-layer guard',
    'Page lost the isAdmin() fallback guard'
);

// ─────────────────────────────────────────────────────────────────────────────
section('6. JS — sends global CSRF_TOKEN via X-CSRF-Token header');
// ─────────────────────────────────────────────────────────────────────────────

check(
    (bool) preg_match("/'X-CSRF-Token'\\s*:\\s*CSRF_TOKEN/", $ui),
    'JS attaches X-CSRF-Token: CSRF_TOKEN header on POSTs',
    'JS no longer sends X-CSRF-Token header — csrf_check() will reject every request'
);

check(
    !preg_match("/data\\.csrf_token\\s*=\\s*CSRF_TOKEN/", $ui)
 && !preg_match("/data\\.append\\s*\\(\\s*['\"]csrf_token['\"]/", $ui),
    'JS does NOT send token in body as csrf_token (legacy field name)',
    'JS still attaches legacy csrf_token body field — should be X-CSRF-Token header'
);

check(
    str_contains($ui, 'const BACKUP_API'),
    'JS keeps BACKUP_API endpoint constant',
    'JS lost BACKUP_API constant — every fetch() will fail'
);

foreach (['createBackup', 'restoreBackup', 'uploadRestore', 'deleteBackup'] as $fn) {
    check(
        (bool) preg_match('/function\s+' . $fn . '\s*\(/', $ui),
        "JS still defines $fn()",
        "JS lost the $fn() handler — corresponding button is dead"
    );
}

check(
    (bool) preg_match('/function\s+backupPost\s*\(/', $ui),
    'JS still defines the shared backupPost() helper',
    'JS lost backupPost() — all four buttons would break'
);

// ─────────────────────────────────────────────────────────────────────────────
section('7. Button → handler wiring intact');
// ─────────────────────────────────────────────────────────────────────────────

foreach ([
    'createBackup()'     => 'Generate Backup',
    'uploadRestore()'    => 'Upload & Restore',
    "restoreBackup('"    => 'Restore (per row)',
    "deleteBackup('"     => 'Delete (per row)',
] as $needle => $label) {
    check(
        str_contains($ui, $needle),
        "Page wires the \"$label\" button to its JS handler",
        "Page no longer wires \"$label\" — UI control is dead"
    );
}

// ─────────────────────────────────────────────────────────────────────────────
echo "\n\033[1m═════════════════════════════════════════════\033[0m\n";
echo "Passes: $passes  Failures: $failures\n";
if ($failures === 0) {
    echo "\033[32m✅ Backup & Restore CSRF invariants intact.\033[0m\n\n";
    exit(0);
}
echo "\033[31m❌ Backup & Restore CSRF regression — see failures above.\033[0m\n\n";
exit(1);
