<?php
/**
 * Backup & Restore — CSRF Regression + Functional Invariants
 *
 * Locks in the Option-A fix for the "Invalid or expired request. Refresh the
 * page and try again." failure on every action of the Backup & Restore page
 * (Generate Backup, Restore from File, Upload & Restore, Delete).
 *
 * Root cause that this suite guards against:
 *   - The page used a custom $_SESSION['backup_csrf_token'] (generated by a
 *     local generateCsrfToken() helper) that was created server-side but
 *     NEVER echoed into the JS. The JS sent the global CSRF_TOKEN instead,
 *     and the API checked the custom token, so hash_equals() always failed.
 *
 * Fix that this suite enforces:
 *   - api/backup_actions.php uses the canonical csrf_check() helper from
 *     helpers.php (§21 of .claude/security.md). No custom token logic.
 *   - app/constant/settings/backup_restore.php no longer defines a custom
 *     token; its JS sends the global CSRF_TOKEN via the X-CSRF-Token header,
 *     which is exactly what csrf_check() reads.
 *
 * The suite also pins functional invariants (php -l, required actions,
 * required JS handlers, permission gates) so future edits don't silently
 * break the page in a different way.
 *
 * Run:  php tests/test_backup_restore_csrf_cli.php
 *   Exit 0 = all pass (safe to commit / push)
 *   Exit 1 = failures  (push blocked — fix before pushing)
 */

error_reporting(E_ALL & ~E_DEPRECATED);

$root     = dirname(__DIR__);
$failures = 0;
$passes   = 0;

function pass(string $m): void    { global $passes;   $passes++;   echo "  \033[32m✅\033[0m $m\n"; }
function fail(string $m): void    { global $failures; $failures++; echo "  \033[31m❌ $m\033[0m\n"; }
function section(string $t): void { echo "\n\033[1m── $t ──\033[0m\n"; }
function check(bool $cond, string $ok, string $ko): void { $cond ? pass($ok) : fail($ko); }

echo "\n\033[1m═══ Backup & Restore — CSRF Regression Guard ═══\033[0m\n";

$apiFile  = $root . '/api/backup_actions.php';
$uiFile   = $root . '/app/constant/settings/backup_restore.php';
$helpers  = $root . '/helpers.php';
$header   = $root . '/header.php';

// ─────────────────────────────────────────────────────────────────────────────
section('1. Both files exist and are syntactically valid PHP');
// ─────────────────────────────────────────────────────────────────────────────

foreach ([$apiFile, $uiFile, $helpers, $header] as $f) {
    $rel = str_replace($root . DIRECTORY_SEPARATOR, '', $f);
    check(is_file($f), "$rel exists", "$rel is missing");
}

foreach ([$apiFile, $uiFile] as $f) {
    $rel = str_replace($root . DIRECTORY_SEPARATOR, '', $f);
    $out = [];
    $code = 0;
    exec('php -l ' . escapeshellarg($f) . ' 2>&1', $out, $code);
    check($code === 0, "$rel passes php -l", "$rel has PHP syntax errors: " . implode(' | ', $out));
}

$api = is_file($apiFile) ? file_get_contents($apiFile) : '';
$ui  = is_file($uiFile)  ? file_get_contents($uiFile)  : '';
$hlp = is_file($helpers) ? file_get_contents($helpers) : '';
$hdr = is_file($header)  ? file_get_contents($header)  : '';

// ─────────────────────────────────────────────────────────────────────────────
section('2. Canonical csrf_check() helper is still in place');
// ─────────────────────────────────────────────────────────────────────────────

check(
    (bool) preg_match('/function\s+csrf_check\s*\(/', $hlp),
    'helpers.php declares csrf_check()',
    'helpers.php no longer declares csrf_check() — Option-A fix relies on it'
);

check(
    (bool) preg_match('/function\s+csrf_token\s*\(/', $hlp),
    'helpers.php declares csrf_token()',
    'helpers.php no longer declares csrf_token() — header.php depends on it'
);

check(
    str_contains($hlp, "\$_POST['_csrf']") && str_contains($hlp, "HTTP_X_CSRF_TOKEN"),
    'csrf_check() accepts both _csrf POST field and X-CSRF-Token header',
    'csrf_check() transport contract changed — backup page sends X-CSRF-Token; update accordingly'
);

check(
    str_contains($hdr, 'CSRF_TOKEN') && str_contains($hdr, 'csrf_token()'),
    'header.php exposes the global CSRF_TOKEN JS constant from csrf_token()',
    'header.php no longer exposes CSRF_TOKEN — backup page JS depends on it'
);

// ─────────────────────────────────────────────────────────────────────────────
section('3. api/backup_actions.php — Option-A fix invariants');
// ─────────────────────────────────────────────────────────────────────────────

check(
    !str_contains($api, 'backup_csrf_token'),
    'API no longer references the legacy $_SESSION[\'backup_csrf_token\']',
    'API still references backup_csrf_token — legacy CSRF leak NOT removed'
);

check(
    (bool) preg_match('/\bcsrf_check\s*\(\s*\)\s*;/', $api),
    'API invokes csrf_check();',
    'API does not call csrf_check() — CSRF protection is OFF or non-canonical'
);

check(
    !preg_match('/hash_equals\s*\(\s*\$_SESSION\[[\'"]backup_csrf_token/', $api),
    'API does not hand-roll hash_equals() against backup_csrf_token',
    'API still hand-rolls the broken CSRF comparison — Option-A not applied'
);

check(
    !str_contains($api, "Invalid or expired request"),
    'API no longer carries the hard-coded "Invalid or expired request" string',
    'API still ships the old CSRF rejection message — fix is incomplete'
);

check(
    str_contains($api, "require_once __DIR__ . '/../roots.php'"),
    'API still requires roots.php (which loads helpers.php → csrf_check)',
    'API no longer requires roots.php — csrf_check() will be undefined'
);

// ─────────────────────────────────────────────────────────────────────────────
section('4. api/backup_actions.php — all 4 actions still wired');
// ─────────────────────────────────────────────────────────────────────────────

foreach (['create_backup', 'restore_backup', 'delete_backup', 'upload_restore'] as $act) {
    check(
        (bool) preg_match('/case\s+[\'"]' . $act . '[\'"]\s*:/', $api),
        "API handles action: $act",
        "API no longer handles action: $act — backup page would break"
    );
}

check(
    (bool) preg_match("/canDelete\\s*\\(\\s*['\"]backup_restore['\"]\\s*\\)/", $api),
    'API enforces canDelete(\'backup_restore\') permission gate',
    'API has lost the backup_restore permission gate — anyone could create/restore'
);

// ─────────────────────────────────────────────────────────────────────────────
section('5. app/constant/settings/backup_restore.php — page invariants');
// ─────────────────────────────────────────────────────────────────────────────

check(
    !preg_match('/function\s+generateCsrfToken\s*\(/', $ui),
    'Page no longer defines local generateCsrfToken()',
    'Page still defines generateCsrfToken() — legacy duplicate CSRF system'
);

check(
    !str_contains($ui, "\$_SESSION['backup_csrf_token']")
 && !str_contains($ui, '$_SESSION["backup_csrf_token"]'),
    'Page no longer reads or writes $_SESSION[\'backup_csrf_token\']',
    'Page still touches $_SESSION[\'backup_csrf_token\'] — Option-A incomplete'
);

check(
    !preg_match('/\$csrfToken\s*=\s*generateCsrfToken\s*\(/', $ui),
    'Page no longer calls generateCsrfToken()',
    'Page still calls the removed generateCsrfToken() — fatal error at runtime'
);

check(
    (bool) preg_match("/autoEnforcePermission\\s*\\(\\s*['\"]backup_restore['\"]\\s*\\)/", $ui),
    'Page still enforces backup_restore permission via autoEnforcePermission',
    'Page no longer enforces backup_restore permission — non-admins could load it'
);

check(
    str_contains($ui, 'if (!isAdmin())'),
    'Page still has the isAdmin() second-layer guard',
    'Page lost the isAdmin() fallback guard'
);

// ─────────────────────────────────────────────────────────────────────────────
section('6. JS — sends global CSRF_TOKEN via X-CSRF-Token header');
// ─────────────────────────────────────────────────────────────────────────────

check(
    (bool) preg_match("/'X-CSRF-Token'\\s*:\\s*CSRF_TOKEN/", $ui),
    'JS attaches X-CSRF-Token: CSRF_TOKEN header on POSTs',
    'JS no longer sends X-CSRF-Token header — csrf_check() will reject every request'
);

check(
    !preg_match("/data\\.csrf_token\\s*=\\s*CSRF_TOKEN/", $ui)
 && !preg_match("/data\\.append\\s*\\(\\s*['\"]csrf_token['\"]/", $ui),
    'JS does NOT send token in body as csrf_token (legacy field name)',
    'JS still attaches legacy csrf_token body field — should be X-CSRF-Token header'
);

check(
    str_contains($ui, 'const BACKUP_API'),
    'JS keeps BACKUP_API endpoint constant',
    'JS lost BACKUP_API constant — every fetch() will fail'
);

foreach (['createBackup', 'restoreBackup', 'uploadRestore', 'deleteBackup'] as $fn) {
    check(
        (bool) preg_match('/function\s+' . $fn . '\s*\(/', $ui),
        "JS still defines $fn()",
        "JS lost the $fn() handler — corresponding button is dead"
    );
}

check(
    (bool) preg_match('/function\s+backupPost\s*\(/', $ui),
    'JS still defines the shared backupPost() helper',
    'JS lost backupPost() — all four buttons would break'
);

// ─────────────────────────────────────────────────────────────────────────────
section('7. Button → handler wiring intact');
// ─────────────────────────────────────────────────────────────────────────────

foreach ([
    'createBackup()'     => 'Generate Backup',
    'uploadRestore()'    => 'Upload & Restore',
    "restoreBackup('"    => 'Restore (per row)',
    "deleteBackup('"     => 'Delete (per row)',
] as $needle => $label) {
    check(
        str_contains($ui, $needle),
        "Page wires the \"$label\" button to its JS handler",
        "Page no longer wires \"$label\" — UI control is dead"
    );
}

// ─────────────────────────────────────────────────────────────────────────────
section('8. Single backup directory — all components agree on backups/');
// ─────────────────────────────────────────────────────────────────────────────
//
// Bug class this guards against: the page listed files from one folder while
// the API created/restored/deleted in a different folder, so every Delete
// and Restore action returned "File not found" even though the file existed
// somewhere else on disk. Fixed by routing all components at ROOT_DIR/backups/.
//
// api/download_backup.php (a duplicate, unauthenticated-on-create/list/
// delete backup implementation embedded as a tab in system_settings.php) was
// removed entirely — the real Backup page/menu item always used
// app/constant/settings/download_backup.php, which is the only download path
// left and is checked below.

$dlPage = $root . '/app/constant/settings/download_backup.php';

check(is_file($dlPage), 'app/constant/settings/download_backup.php exists', 'app/constant/settings/download_backup.php is missing');
check(!is_file($root . '/api/create_backup.php'), 'api/create_backup.php (unauthenticated duplicate) has been removed', 'api/create_backup.php still exists — the unauthenticated duplicate backup creator is back');
check(!is_file($root . '/api/get_backup_list.php'), 'api/get_backup_list.php (unauthenticated duplicate) has been removed', 'api/get_backup_list.php still exists — the unauthenticated duplicate backup lister is back');
check(!is_file($root . '/api/download_backup.php'), 'api/download_backup.php (duplicate) has been removed', 'api/download_backup.php still exists — the duplicate download path is back');
check(!is_file($root . '/api/delete_backup.php'), 'api/delete_backup.php (unauthenticated duplicate) has been removed', 'api/delete_backup.php still exists — the unauthenticated duplicate backup deleter is back');
check(!is_file($root . '/api/save_backup_settings.php'), 'api/save_backup_settings.php (duplicate) has been removed', 'api/save_backup_settings.php still exists — the duplicate settings saver is back');

$dlPageSrc = is_file($dlPage) ? file_get_contents($dlPage) : '';

// Canonical path = ROOT_DIR . '/backups/' (top-level backups folder).
// Every component must point at this same physical directory.

check(
    (bool) preg_match("#\\\$backupsDir\\s*=\\s*ROOT_DIR\\s*\\.\\s*['\"]/backups/['\"]#", $api),
    'API uses ROOT_DIR . \'/backups/\' as the backup directory',
    'API uses a non-canonical backup directory path'
);

check(
    !str_contains($api, '/uploads/system/backups/'),
    'API no longer references the legacy /uploads/system/backups/ path',
    'API still references /uploads/system/backups/ — directory mismatch will reappear'
);

check(
    (bool) preg_match("#\\\$backupsDir\\s*=\\s*__DIR__\\s*\\.\\s*['\"]/\\.\\./\\.\\./\\.\\./backups/['\"]#", $ui),
    'Page uses __DIR__ . \'/../../../backups/\' (resolves to ROOT_DIR/backups/)',
    'Page no longer uses the canonical backups/ path'
);

check(
    str_contains($dlPageSrc, "__DIR__ . '/../../../backups/'"),
    'app/constant/settings/download_backup.php uses __DIR__ . \'/../../../backups/\'',
    'app/constant/settings/download_backup.php no longer matches the canonical path'
);

// ─────────────────────────────────────────────────────────────────────────────
section('9. backups/ is hardened against direct HTTP access');
// ─────────────────────────────────────────────────────────────────────────────

$backupsDirPath = $root . '/backups';
$htaccess       = $backupsDirPath . '/.htaccess';

check(
    is_dir($backupsDirPath),
    'backups/ directory exists on disk',
    'backups/ directory is missing — runtime will mkdir it but .htaccess will be absent'
);

check(
    is_file($htaccess),
    'backups/.htaccess exists',
    'backups/.htaccess is missing — .sql dumps would be directly downloadable'
);

$htAccessSrc = is_file($htaccess) ? file_get_contents($htaccess) : '';

check(
    (bool) preg_match('/^\s*Require\s+all\s+denied\s*$/mi', $htAccessSrc),
    '.htaccess contains a top-level "Require all denied" directive',
    '.htaccess does not deny direct access at the directory level'
);

check(
    str_contains($htAccessSrc, '<FilesMatch') && str_contains($htAccessSrc, 'php'),
    '.htaccess also has the defence-in-depth PHP-execution block',
    '.htaccess is missing the PHP-execution defence-in-depth block'
);

// ─────────────────────────────────────────────────────────────────────────────
section('10. The duplicate, unauthenticated "Backup" tab inside Settings is gone');
// ─────────────────────────────────────────────────────────────────────────────
//
// system_settings.php used to embed a second, entirely separate Backup
// feature (its own tab, its own 5 API files) alongside the real Backup page.
// That duplicate had NO auth check at all on create/list/delete (the
// permission check was commented out), hardcoded a Windows-only mysqldump
// path that would fail on the Linux production server, and could never
// download its own .zip output (download only accepted .sql). Removed
// entirely rather than fixed, since the real Backup page already covers
// everything it did.

$settingsFile = $root . '/app/constant/settings/system_settings.php';
check(is_file($settingsFile), 'system_settings.php exists', 'system_settings.php is missing');
$settingsSrc = is_file($settingsFile) ? file_get_contents($settingsFile) : '';

foreach ([
    'id="backup-tab"'        => 'the Backup tab nav button',
    'id="backup"'            => 'the Backup tab-pane content',
    "id=\"createBackup\""    => 'the Create Backup button/handler',
    'saveBackupSettings'     => 'the Save Backup Settings handler',
    'loadBackupList'         => 'the backup-list loader',
    'backup_frequency'       => 'the backup frequency scheduler field',
    'backup_retention'       => 'the backup retention scheduler field',
] as $needle => $label) {
    check(
        !str_contains($settingsSrc, $needle),
        "system_settings.php no longer contains $label",
        "system_settings.php still contains $label — the duplicate Backup tab was not fully removed"
    );
}

// ─────────────────────────────────────────────────────────────────────────────
section('11. Backup entry point moved into Settings > Admin, not touching the real page');
// ─────────────────────────────────────────────────────────────────────────────
//
// Per request: "Backup" moved from being its own standalone item in the top
// Settings dropdown to living inside Settings > Admin (system_settings.php),
// at the end of its tab list — but as a PLAIN LINK to the existing,
// unmodified backup_restore.php page, not a re-implementation. header.php's
// old standalone dropdown item is removed; backup_restore.php itself must
// stay byte-for-byte untouched.

check(
    !preg_match("#<li><a class=\"dropdown-item\" href=\"<\\?= getUrl\\('backup_restore'\\) \\?>\"><i class=\"bi bi-database\"></i> Backup</a></li>#", $hdr),
    'header.php no longer has a standalone "Backup" item in the Settings dropdown',
    'header.php still has the old standalone Backup dropdown item — should have moved into Settings > Admin'
);

check(
    (bool) preg_match('/href="<\?= getUrl\(\'backup_restore\'\) \?>"/', $settingsSrc),
    'system_settings.php now links to backup_restore.php from within Settings > Admin',
    'system_settings.php has no link to backup_restore.php — the Backup entry point is missing entirely'
);

// The link must be a genuine navigation (no data-bs-toggle="tab"), so it
// opens the real page rather than trying to render a local tab-pane.
if (preg_match('/<a class="list-group-item[^"]*"\s+href="<\?= getUrl\(\'backup_restore\'\) \?>">/s', $settingsSrc)) {
    pass('the Backup link is a plain navigation (no data-bs-toggle="tab") — opens the real page, not a local pane');
} else {
    fail('the Backup link is not structured as a plain nav link — check it isn\'t wired as a Bootstrap tab pointing at a (now-deleted) local pane');
}

// backup_restore.php itself must keep working exactly as before this move —
// already thoroughly verified by sections 1-9 above (CSRF, permission gate,
// all 4 actions wired, directory paths); nothing here re-touches that file.

// ─────────────────────────────────────────────────────────────────────────────
echo "\n\033[1m═════════════════════════════════════════════\033[0m\n";
echo "Passes: $passes  Failures: $failures\n";
if ($failures === 0) {
    echo "\033[32m✅ Backup & Restore CSRF + directory invariants intact.\033[0m\n\n";
    exit(0);
}
echo "\033[31m❌ Backup & Restore regression — see failures above.\033[0m\n\n";
exit(1);
