<?php
/**
 * Security Phase 1 — DB Cleanup Seed Migration
 * --------------------------------------------
 * Phase 1 of security_implementation_plan.md v2. NO application code is
 * touched in this migration; this is purely a DB normalization step.
 *
 * Goals:
 *
 *   A. Insert the 18 permission keys that are referenced by existing pages
 *      but never seeded in the `permissions` table. Without these rows the
 *      admin cannot grant the permission from user_roles.php, so the page
 *      stays permanently locked for everyone except admin.
 *      All new rows have NO grants in `role_permissions` (default-deny
 *      zero-trust). Admin still passes through via isAdmin(); other roles
 *      must be explicitly granted in the UI.
 *
 *   B. Fix the module_name typo: 'procurement' (lowercase) → 'Procurement'
 *      so user_roles.php groups all procurement permissions together.
 *
 *   C. Fix the blank page_name on the `received_invoices` row so admins can
 *      see what they're ticking.
 *
 * Idempotent: every step uses INSERT IGNORE or a guarded UPDATE so re-runs
 * are no-ops.
 *
 * Default-deny posture: NO role_permissions rows are inserted alongside
 * these permissions, so non-admin roles cannot access the new pages until
 * an admin explicitly ticks the box in /user_roles.php. Admin always
 * bypasses via isAdmin().
 */

require_once __DIR__ . '/../roots.php';
global $pdo;

echo "Starting migration: Security Phase 1 DB cleanup...\n";

try {
    // ── A. Seed missing permission keys ─────────────────────────────────
    //
    // Each row: [page_key, page_name, description, module_name].
    // page_key is what existing code calls via canX('the_key').
    // The list was generated by scratch/security_audit.php and matches
    // the gaps documented in security_audit_2026_05_24.md section A2.
    //
    $seeds = [
        // ── Procurement ─────────────────────────────────────
        ['supplier_payments', 'Supplier Payments',  'Manage supplier payment records',       'Procurement'],
        ['nip_materials',     'NIP Materials',      'Manage NIP material lists & inspections','Procurement'],
        ['purchase',          'Purchase (General)', 'Legacy generic procurement key — to be normalized in Phase 5','Procurement'],

        // ── Reports ─────────────────────────────────────────
        ['reports',           'Reports (Index)',          'Invoice reports index page',          'Reports'],
        ['financial_reports', 'Financial Reports',        'Balance sheet, trial balance, cash flow, financial statements, audit report — all gated by this single key','Reports'],
        ['asset_report',      'Asset Report',             'Asset inventory & depreciation report','Reports'],
        ['customer_analysis', 'Customer Analysis',        'Customer behaviour & sales analysis',  'Reports'],
        ['employee_report',   'Employee Report',          'Employee performance / leave report',  'Reports'],
        ['product_analysis',  'Product Analysis',         'Product movement & profitability',     'Reports'],
        ['trends_analysis',   'Trends Analysis',          'Sales & purchase trend analysis',      'Reports'],

        // ── Documents ───────────────────────────────────────
        ['documents',         'Documents (General)',      'Generic documents-module gate (library, e-signatures landing)','Documents'],
        ['compliance',        'Compliance (Legacy)',      'Legacy compliance key — to be normalized to compliance_documents in Phase 5','Documents'],
        ['loan_documents',    'Loan Documents',           'Loan-related document storage',        'Documents'],

        // ── System Settings ────────────────────────────────
        ['admin',             'Admin (Legacy)',           'Legacy admin gate used by compliance_report — to be normalized in Phase 5','System Settings'],
        ['activity_log',      'Activity Log',             'View the system-wide activity log',    'System Settings'],
        ['profile',           'My Profile',               'User self-service profile page',       'System Settings'],

        // ── Finance ─────────────────────────────────────────
        ['payment_create',    'Record Payment',           'Invoice payment recording page',       'Finance'],

        // ── Human Resources ────────────────────────────────
        ['payslip',           'Payslip',                  'Employee payslip view & print',        'Human Resources'],
    ];

    // INSERT IGNORE keyed on the UNIQUE INDEX on permissions.page_key.
    // We don't know the exact unique index name across sites, but
    // INSERT IGNORE INTO ... is safe even when only the page_key column
    // happens to have a UNIQUE constraint, OR when there is no unique
    // constraint at all — in which case we fall back to an explicit
    // existence check.
    $insert = $pdo->prepare("
        INSERT INTO permissions (page_key, page_name, description, module_name, created_at)
        SELECT ?, ?, ?, ?, NOW()
        WHERE NOT EXISTS (SELECT 1 FROM permissions p WHERE p.page_key = ?)
    ");

    $added = 0;
    $existing = 0;
    foreach ($seeds as [$key, $name, $desc, $module]) {
        $insert->execute([$key, $name, $desc, $module, $key]);
        if ($insert->rowCount() > 0) {
            $added++;
            echo "  + Seeded permission: '$key' ($name) → $module\n";
        } else {
            $existing++;
        }
    }
    echo "  Summary: $added new row(s), $existing already present.\n";

    // ── B. Fix module_name typo ─────────────────────────────────────────
    $typo = $pdo->exec("UPDATE permissions SET module_name = 'Procurement' WHERE module_name = 'procurement'");
    if ($typo > 0) {
        echo "  + Renamed module 'procurement' → 'Procurement' on $typo row(s).\n";
    } else {
        echo "  · No 'procurement' (lowercase) rows to rename.\n";
    }

    // ── C. Fix blank received_invoices label ────────────────────────────
    $blank = $pdo->exec("UPDATE permissions
                         SET page_name = 'Received Invoices'
                         WHERE page_key = 'received_invoices'
                           AND (page_name = '' OR page_name IS NULL)");
    if ($blank > 0) {
        echo "  + Filled blank page_name on '$blank' received_invoices row(s).\n";
    } else {
        echo "  · received_invoices row already has a page_name.\n";
    }

    echo "Migration complete.\n";

} catch (PDOException $e) {
    echo "Migration failed: " . $e->getMessage() . "\n";
    exit(1);
}
