<?php
/**
 * Migration: add recurring_profile_id to expenses
 *
 * Closes the traceability gap: expenses generated by the recurring engine
 * had no back-reference to their profile. This column is metadata only —
 * it is never read by any GL posting function, so there is zero risk of
 * double-posting.
 *
 * Idempotent: guarded by SHOW COLUMNS check.
 */

require_once __DIR__ . '/../roots.php';
global $pdo;

try {
    // Guard: skip if column already exists
    $cols = $pdo->query("SHOW COLUMNS FROM expenses LIKE 'recurring_profile_id'")->fetchAll();
    if (!empty($cols)) {
        echo "recurring_profile_id already exists on expenses — skipping.\n";
        exit(0);
    }

    $pdo->exec("ALTER TABLE expenses ADD COLUMN recurring_profile_id INT NULL DEFAULT NULL AFTER notes");

    echo "OK: recurring_profile_id added to expenses.\n";
    exit(0);

} catch (PDOException $e) {
    echo "ERROR: " . $e->getMessage() . "\n";
    exit(1);
}
